---
version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"  # Main gateway
      - "4571:4571"
    environment:
      - SERVICES=s3,ec2,lambda,cloudformation
      - DEBUG=1
    volumes:
      - ./volume:/var/lib/localstack
